export default {
  transaction: {
    id: 'txn_1IIzvc2nImeJXwdJYlZAxqya',
    object: 'balance_transaction',
    amount: 100,
    available_on: 1613001600,
    created: 1612891387,
    currency: 'usd',
    description: 'Subscription creation',
    exchange_rate: null,
    fee: 33,
    fee_details: [
      {
        amount: 33,
        application: null,
        currency: 'usd',
        description: 'Stripe processing fees',
        type: 'stripe_fee',
      },
    ],
    net: 67,
    reporting_category: 'charge',
    source: {
      id: 'ch_1IIzvb2nImeJXwdJUPVMoWAN',
      object: 'charge',
      amount: 100,
      amount_captured: 100,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: 'txn_1IIzvc2nImeJXwdJYlZAxqya',
      billing_details: {
        address: {
          city: null,
          country: null,
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: null,
        name: null,
        phone: null,
      },
      calculated_statement_descriptor: 'EGGHEAD.IO TRAINING',
      captured: true,
      created: 1612891387,
      currency: 'usd',
      customer: 'cus_IupaViEnkrH0Lw',
      description: 'Subscription creation',
      destination: null,
      dispute: null,
      disputed: false,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: {
        id: 'in_1IIzvb2nImeJXwdJw3hlkGXt',
        object: 'invoice',
        account_country: 'US',
        account_name: 'egghead.io',
        account_tax_ids: null,
        amount_due: 100,
        amount_paid: 100,
        amount_remaining: 0,
        application_fee_amount: null,
        attempt_count: 1,
        attempted: true,
        auto_advance: false,
        billing_reason: 'subscription_create',
        charge: 'ch_1IIzvb2nImeJXwdJUPVMoWAN',
        collection_method: 'charge_automatically',
        created: 1612891387,
        currency: 'usd',
        custom_fields: null,
        customer: 'cus_IupaViEnkrH0Lw',
        customer_address: null,
        customer_email: 'email1@example.com',
        customer_name: null,
        customer_phone: null,
        customer_shipping: null,
        customer_tax_exempt: 'none',
        customer_tax_ids: [],
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [],
        description: null,
        discount: null,
        discounts: [],
        due_date: null,
        ending_balance: 0,
        footer: null,
        hosted_invoice_url:
          'https://invoice.stripe.com/i/acct_102eKx2nImeJXwdJ/invst_IupayrEQt5psQZBYKmg1qca6D88fVPF',
        invoice_pdf:
          'https://pay.stripe.com/invoice/acct_102eKx2nImeJXwdJ/invst_IupayrEQt5psQZBYKmg1qca6D88fVPF/pdf',
        last_finalization_error: null,
        lines: {
          object: 'list',
          data: [
            {
              id: 'il_1IIzvb2nImeJXwdJdaHeo5fE',
              object: 'line_item',
              amount: 100,
              currency: 'usd',
              description: '1 × Egghead Membership (Test) (at $1.00 / month)',
              discount_amounts: [],
              discountable: true,
              discounts: [],
              livemode: false,
              metadata: {},
              period: {
                end: 1615310586,
                start: 1612891386,
              },
              plan: {
                id: 'test_plan_15a57b17e51b8c9dbc0efb0ba6f15c3b',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 100,
                amount_decimal: '100',
                billing_scheme: 'per_unit',
                created: 1612891385,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: false,
                metadata: {},
                nickname: 'test plan',
                product: 'test_egghead_product',
                tiers: null,
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: 'licensed',
              },
              price: {
                id: 'test_plan_15a57b17e51b8c9dbc0efb0ba6f15c3b',
                object: 'price',
                active: true,
                billing_scheme: 'per_unit',
                created: 1612891385,
                currency: 'usd',
                livemode: false,
                lookup_key: null,
                metadata: {},
                nickname: 'test plan',
                product: 'test_egghead_product',
                recurring: {
                  aggregate_usage: null,
                  interval: 'month',
                  interval_count: 1,
                  trial_period_days: null,
                  usage_type: 'licensed',
                },
                tiers_mode: null,
                transform_quantity: null,
                type: 'recurring',
                unit_amount: 100,
                unit_amount_decimal: '100',
              },
              proration: false,
              quantity: 1,
              subscription: 'sub_IupaQo4PtythC5',
              subscription_item: 'si_IupaipH9i8mVxz',
              tax_amounts: [],
              tax_rates: [],
              type: 'subscription',
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/invoices/in_1IIzvb2nImeJXwdJw3hlkGXt/lines',
        },
        livemode: false,
        metadata: {},
        next_payment_attempt: null,
        number: '1E4C6D7C-0001',
        paid: true,
        payment_intent: 'pi_1IIzvb2nImeJXwdJEc4VDKXY',
        payment_settings: {
          payment_method_options: null,
          payment_method_types: null,
        },
        period_end: 1612891386,
        period_start: 1612891386,
        post_payment_credit_notes_amount: 0,
        pre_payment_credit_notes_amount: 0,
        receipt_number: null,
        starting_balance: 0,
        statement_descriptor: null,
        status: 'paid',
        status_transitions: {
          finalized_at: 1612891386,
          marked_uncollectible_at: null,
          paid_at: 1612891386,
          voided_at: null,
        },
        subscription: 'sub_IupaQo4PtythC5',
        subtotal: 100,
        tax: null,
        tax_percent: null,
        total: 100,
        total_discount_amounts: [],
        total_tax_amounts: [],
        transfer_data: null,
        webhooks_delivered_at: null,
      },
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: {
        network_status: 'approved_by_network',
        reason: null,
        risk_level: 'normal',
        risk_score: 21,
        seller_message: 'Payment complete.',
        type: 'authorized',
      },
      paid: true,
      payment_intent: 'pi_1IIzvb2nImeJXwdJEc4VDKXY',
      payment_method: 'card_1IIzva2nImeJXwdJ3B70iDBu',
      payment_method_details: {
        card: {
          brand: 'visa',
          checks: {
            address_line1_check: null,
            address_postal_code_check: null,
            cvc_check: 'pass',
          },
          country: 'US',
          exp_month: 2,
          exp_year: 2022,
          fingerprint: 'cim83Wvk3uDiY7F5',
          funding: 'credit',
          installments: null,
          last4: '4242',
          network: 'visa',
          three_d_secure: null,
          wallet: null,
        },
        type: 'card',
      },
      receipt_email: null,
      receipt_number: null,
      receipt_url:
        'https://pay.stripe.com/receipts/acct_102eKx2nImeJXwdJ/ch_1IIzvb2nImeJXwdJUPVMoWAN/rcpt_Iupa0DKQMX28AsoJcEtg4VS79rMnnA5',
      refunded: false,
      refunds: {
        object: 'list',
        data: [],
        has_more: false,
        total_count: 0,
        url: '/v1/charges/ch_1IIzvb2nImeJXwdJUPVMoWAN/refunds',
      },
      review: null,
      shipping: null,
      source: {
        id: 'card_1IIzva2nImeJXwdJ3B70iDBu',
        object: 'card',
        address_city: null,
        address_country: null,
        address_line1: null,
        address_line1_check: null,
        address_line2: null,
        address_state: null,
        address_zip: null,
        address_zip_check: null,
        brand: 'Visa',
        country: 'US',
        customer: 'cus_IupaViEnkrH0Lw',
        cvc_check: 'pass',
        dynamic_last4: null,
        exp_month: 2,
        exp_year: 2022,
        fingerprint: 'cim83Wvk3uDiY7F5',
        funding: 'credit',
        last4: '4242',
        metadata: {},
        name: null,
        tokenization_method: null,
      },
      source_transfer: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
    status: 'pending',
    type: 'charge',
  },
  lineItems: [
    {
      id: 'il_1IIzvb2nImeJXwdJdaHeo5fE',
      object: 'line_item',
      amount: 100,
      currency: 'usd',
      description: '1 × Egghead Membership (Test) (at $1.00 / month)',
      discount_amounts: [],
      discountable: true,
      discounts: [],
      livemode: false,
      metadata: {},
      period: {
        end: 1615310586,
        start: 1612891386,
      },
      plan: {
        id: 'test_plan_15a57b17e51b8c9dbc0efb0ba6f15c3b',
        object: 'plan',
        active: true,
        aggregate_usage: null,
        amount: 100,
        amount_decimal: '100',
        billing_scheme: 'per_unit',
        created: 1612891385,
        currency: 'usd',
        interval: 'month',
        interval_count: 1,
        livemode: false,
        metadata: {},
        nickname: 'test plan',
        product: 'test_egghead_product',
        tiers: null,
        tiers_mode: null,
        transform_usage: null,
        trial_period_days: null,
        usage_type: 'licensed',
      },
      price: {
        id: 'test_plan_15a57b17e51b8c9dbc0efb0ba6f15c3b',
        object: 'price',
        active: true,
        billing_scheme: 'per_unit',
        created: 1612891385,
        currency: 'usd',
        livemode: false,
        lookup_key: null,
        metadata: {},
        nickname: 'test plan',
        product: 'test_egghead_product',
        recurring: {
          aggregate_usage: null,
          interval: 'month',
          interval_count: 1,
          trial_period_days: null,
          usage_type: 'licensed',
        },
        tiers_mode: null,
        transform_quantity: null,
        type: 'recurring',
        unit_amount: 100,
        unit_amount_decimal: '100',
      },
      proration: false,
      quantity: 1,
      subscription: 'sub_IupaQo4PtythC5',
      subscription_item: 'si_IupaipH9i8mVxz',
      tax_amounts: [],
      tax_rates: [],
      type: 'subscription',
    },
  ],
}
